version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: postgres
    environment:
      - POSTGRES_DB=threat_intel
      - POSTGRES_USER=tiuser
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - /opt/project/postgres/data:/var/lib/postgresql/data
      - /opt/project/postgres/init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    command: postgres -c listen_addresses='*' -c max_connections=200
