# Network
bind 0.0.0.0
protected-mode yes
port 6379

# Security
requirepass Location@1234

# Persistence
save 900 1
save 300 10
save 60 10000
stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes
dbfilename dump.rdb
dir /data

# Logging
loglevel notice
logfile ""

# Max memory
maxmemory 512mb
maxmemory-policy allkeys-lru

# Streams
stream-node-max-bytes 4096
stream-node-max-entries 100

# Performance
timeout 300
tcp-keepalive 300
